-- Workspace rules wiki https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- Add your workspace rules here. Increment the workspace number as you go. Do not have duplicate workspaces.
-- config.workspaces_current (generated by scripts/monitors.sh on portable
-- machines) overrides these with location-specific rules. This static
-- block is only the fallback used when that file doesn't exist - i.e. on
-- this desktop, whose setup never changes.
if not pcall(require, "config.workspaces_current") then
    hl.workspace_rule({ workspace = "name:gaming", monitor = PRIMARY_MONITOR, default = true })
    hl.workspace_rule({ workspace = "1", monitor = MONITOR1, default = true, persistent = true })
    hl.workspace_rule({ workspace = "2", monitor = MONITOR1, default = true, persistent = true })
    hl.workspace_rule({ workspace = "3", monitor = MONITOR1, default = true, persistent = true })
    -- hl.workspace_rule({ workspace = "4", monitor = MONITOR2, default = true, persistent = true })
    -- hl.workspace_rule({ workspace = "5", monitor = MONITOR2, default = true, persistent = true })
    -- hl.workspace_rule({ workspace = "6", monitor = MONITOR2, default = true, persistent = true })
end